Desarrollo de API

Se deben crean 6 funciones para los endpoints que se consumirán en la API, tenedra un decorador por cada una (@app.get(‘/’)).

1. def peliculas_idioma( Idioma: str ): Se ingresa un idioma (como están escritos en el dataset, no hay que traducirlos!). Debe devolver la cantidad de películas producidas en ese idioma.
                    Ejemplo de retorno: X cantidad de películas fueron estrenadas en idioma

2. def peliculas_duracion( Pelicula: str ): Se ingresa una pelicula. Debe devolver la duracion y el año.
                    Ejemplo de retorno: X . Duración: x. Año: xx

3. def franquicia( Franquicia: str ): Se ingresa la franquicia, retornando la cantidad de peliculas, ganancia total y promedio
                    Ejemplo de retorno: La franquicia X posee X peliculas, una ganancia total de x y una ganancia promedio de xx

4. def peliculas_pais( Pais: str ): Se ingresa un país (como están escritos en el dataset, no hay que traducirlos!), retornando la cantidad de peliculas producidas en el mismo.
                    Ejemplo de retorno: Se produjeron X películas en el país X

5. def productoras_exitosas( Productora: str ): Se ingresa la productora, entregandote el revunue total y la cantidad de peliculas que realizo.
                    Ejemplo de retorno: La productora X ha tenido un revenue de x

6. def get_director( nombre_director ): Se ingresa el nombre de un director que se encuentre dentro de un dataset debiendo devolver el éxito del mismo medido a través del retorno. Además, deberá devolver el nombre de cada película con la fecha de lanzamiento, retorno individual, costo y ganancia de la misma, en formato lista.

In [73]:
import numpy as np
import pandas as pd

In [74]:
df = pd.read_csv('C:/Users/cesua/OneDrive/Documentos/Henry/Proyecto_Individual_1/Datasets/movies_dataset_final.csv')

C:\Users\cesua\AppData\Local\Temp\ipykernel_48716\2259615563.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('C:/Users/cesua/OneDrive/Documentos/Henry/Proyecto_Individual_1/Datasets/movies_dataset_final.csv')

In [75]:
pd.set_option('display.max_columns', None)  # Mostrar todas las columnas
df.head(10)

,budget,id,original_language,overview,popularity,production_companies,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,id_btc,name_btc,genero_id,genero_nombre,production_countries,return,release_year
0,30000000.0,862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,['Pixar Animation Studios'],1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,7.7,10194.0,Toy Story Collection,16.0,Animation,United States of America,12.45,1995.0
1,65000000.0,8844,en,When siblings Judy and Peter discover an encha...,17.015539,"['TriStar Pictures', 'Teitler Film', 'Intersco...",1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,NaN,NaN,35.0,Comedy,United States of America,4.04,1995.0
2,0.0,15602,en,A family wedding reignites the ancient feud be...,11.7129,"['Warner Bros.', 'Lancaster Gate']",1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,119050.0,Grumpy Old Men Collection,10751.0,Family,United States of America,0.00,1995.0
3,16000000.0,31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,['Twentieth Century Fox Film Corporation'],1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,NaN,NaN,12.0,Adventure,United States of America,5.09,1995.0
4,0.0,11862,en,Just when George Banks has recovered from his ...,8.387519,"['Sandollar Productions', 'Touchstone Pictures']",1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,96871.0,Father of the Bride Collection,14.0,Fantasy,United States of America,0.00,1995.0
5,60000000.0,949,en,"Obsessive master thief, Neil McCauley leads a ...",17.924927,"['Regency Enterprises', 'Forward Pass', 'Warne...",1995-12-15,187436818.0,170.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Los Angeles Crime Saga,Heat,7.7,NaN,NaN,10751.0,Family,United States of America,3.12,1995.0
6,58000000.0,11860,en,An ugly duckling having undergone a remarkable...,6.677277,"['Paramount Pictures', 'Scott Rudin Production...",1995-12-15,0.0,127.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,You are cordially invited to the most surprisi...,Sabrina,6.2,NaN,NaN,10749.0,Romance,"Germany, United States of America",0.00,1995.0
7,0.0,45325,en,"A mischievous young boy, Tom Sawyer, witnesses...",2.561161,['Walt Disney Pictures'],1995-12-22,0.0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,The Original Bad Boys.,Tom and Huck,5.4,NaN,NaN,35.0,Comedy,United States of America,0.00,1995.0
8,35000000.0,9091,en,International action superstar Jean Claude Van...,5.23158,"['Universal Pictures', 'Imperial Entertainment...",1995-12-22,64350171.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Terror goes into overtime.,Sudden Death,5.5,NaN,NaN,35.0,Comedy,United States of America,1.84,1995.0
9,58000000.0,710,en,James Bond must unmask the mysterious head of ...,14.686036,"['United Artists', 'Eon Productions']",1995-11-16,352194034.0,130.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,No limits. No fears. No substitutes.,GoldenEye,6.6,645.0,James Bond Collection,18.0,Drama,"United Kingdom, United States of America",6.07,1995.0

1. def peliculas_idioma( Idioma: str ):

In [76]:
# Funcion de consulta del numero de peliculas por idioma
def peliculas_idioma(idioma):
    # Selecciona todas las películas del DataFrame 'df' cuya columna 'original_language' contiene el idioma especificado.
    # La función lambda se utiliza para aplicar la operación a cada valor de la columna 'original_language'.
    peliculas_idioma = df[df['original_language'].apply(lambda x: idioma in str(x) if pd.notnull(x) else False)]
    
    # Elimina las filas duplicadas de la película para evitar contar varias veces una misma película.
    peliculas_idioma = peliculas_idioma.drop_duplicates(subset='id')
    
    # Cuenta la cantidad de películas restantes después de eliminar los duplicados
    respuesta = len(peliculas_idioma)
    
    # Devuelve los resultados en un diccionario con claves legibles
    return {'idioma': idioma, 'cantidad de peliculas': respuesta}

In [77]:
df['original_language'].unique()

array(['en', 'fr', 'zh', 'it', 'fa', 'nl', 'de', 'cn', 'ar', 'es', 'ru',
       'sv', 'ja', 'ko', 'sr', 'bn', 'he', 'pt', 'wo', 'ro', 'hu', 'cy',
       'vi', 'cs', 'da', 'no', 'nb', 'pl', 'el', 'sh', 'xx', 'mk', 'bo',
       'ca', 'fi', 'th', 'sk', 'bs', 'hi', 'tr', 'is', 'ps', 'ab', 'eo',
       'ka', 'mn', 'bm', 'zu', 'uk', 'af', 'la', 'et', 'ku', 'fy', 'lv',
       'ta', 'sl', 'tl', 'ur', 'rw', 'id', 'bg', 'mr', 'lt', 'kk', 'ms',
       'sq', nan, '104.0', 'qu', 'te', 'am', 'jv', 'tg', 'ml', 'hr', 'lo',
       'ay', 'kn', 'eu', 'ne', 'pa', 'ky', 'gl', '68.0', 'uz', 'sm', 'mt',
       '82.0', 'hy', 'iu', 'lb', 'si'], dtype=object)

In [78]:
peliculas_idioma('es')

{'idioma': 'es', 'cantidad de peliculas': 992}

2. def peliculas_duracion( Pelicula: str ):

In [79]:
def peliculas_duracion(pelicula):
    
    info_pelicula = df[(df['title'] == pelicula)].drop_duplicates(subset='title')
    pelicula_nombre = info_pelicula['title'].iloc[0]
    duracion_pelicula = str(info_pelicula['runtime'].iloc[0])
    año_pelicula = str(info_pelicula['release_year'].iloc[0])

    return {'pelicula':pelicula_nombre, 'duracion min':duracion_pelicula, 'año':año_pelicula}

In [80]:
peliculas_duracion('Toy Story')

{'pelicula': 'Toy Story', 'duracion min': '81.0', 'año': '1995.0'}

3. def franquicia( Franquicia: str ):

In [81]:
df['name_btc'].unique()

array(['Toy Story Collection', nan, 'Grumpy Old Men Collection', ...,
       'Ducobu Collection', 'Mister Blot Collection',
       'Red Lotus Collection'], dtype=object)

In [82]:
# Funcion de consulta del numero de colecciones de peliculas, su ganancia total y ganancia promedio 
def franquicia(franquicia):

    lista_pelis_franquicia = df[(df['name_btc'] == franquicia)].drop_duplicates(subset='id')

    cantidad_pelis_franq = (lista_pelis_franquicia).shape[0]
    revenue_franq = lista_pelis_franquicia['revenue'].sum()
    promedio_franq = revenue_franq/cantidad_pelis_franq

    return {'franquicia':franquicia, 'cantidad':cantidad_pelis_franq, 'ganancia_total':revenue_franq, 'ganancia_promedio': promedio_franq}

In [83]:
# Control sobre la funcion 
franquicia("James Bond Collection")

{'franquicia': 'James Bond Collection',
 'cantidad': 26,
 'ganancia_total': 7106970239.0,
 'ganancia_promedio': 273345009.1923077}

4. def peliculas_pais( Pais: str ):

In [84]:
# Funcion de consulta del numero de peliculas por pais 2
def peliculas_pais(pais):
    # Selecciona todas las películas del DataFrame 'df' cuya columna 'production_countries' contiene el país especificado.
    # La función lambda se utiliza para aplicar la operación a cada valor de la columna 'production_countries'.
    peliculas_pais = df[df['production_countries'].apply(lambda x: pais in str(x) if pd.notnull(x) else False)]
    
    # Elimina las filas duplicadas de la película para evitar contar varias veces una misma película.
    peliculas_pais = peliculas_pais.drop_duplicates(subset='id')
    
    # Cuenta la cantidad de películas restantes después de eliminar los duplicados.
    respuesta = len(peliculas_pais)
    
    # Devuelve los resultados en un diccionario con claves legibles.
    return {'pais': pais, 'cantidad de peliculas': respuesta}

In [85]:
# Control sobre la funcion
peliculas_pais('Spain')

{'pais': 'Spain', 'cantidad de peliculas': 964}

5. def productoras_exitosas( Productora: str ):

In [86]:
df['production_companies'].unique()

array(["['Pixar Animation Studios']",
       "['TriStar Pictures', 'Teitler Film', 'Interscope Communications']",
       "['Warner Bros.', 'Lancaster Gate']", ...,
       "['Westdeutscher Rundfunk (WDR)', 'Working Title Films', '20th Century Fox Television', 'CanWest Global Communications']",
       "['Sine Olivia']", "['Yermoliev']"], dtype=object)

In [87]:
df['production_companies'] = df['production_companies'].astype(str).str.replace('[','').str.replace(']','').str.replace(',','')

In [88]:
df['production_companies'] = df['production_companies'].astype(str).str.replace('[','').str.replace(']','').str.replace(',','').str.replace('\'', '')

In [89]:
df

,budget,id,original_language,overview,popularity,production_companies,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,id_btc,name_btc,genero_id,genero_nombre,production_countries,return,release_year
0,30000000.0,862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,Pixar Animation Studios,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,7.7,10194.0,Toy Story Collection,16.0,Animation,United States of America,12.45,1995.0
1,65000000.0,8844,en,When siblings Judy and Peter discover an encha...,17.015539,TriStar Pictures Teitler Film Interscope Commu...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,6.9,NaN,NaN,35.0,Comedy,United States of America,4.04,1995.0
2,0.0,15602,en,A family wedding reignites the ancient feud be...,11.7129,Warner Bros. Lancaster Gate,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,119050.0,Grumpy Old Men Collection,10751.0,Family,United States of America,0.00,1995.0
3,16000000.0,31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,Twentieth Century Fox Film Corporation,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,NaN,NaN,12.0,Adventure,United States of America,5.09,1995.0
4,0.0,11862,en,Just when George Banks has recovered from his ...,8.387519,Sandollar Productions Touchstone Pictures,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,96871.0,Father of the Bride Collection,14.0,Fantasy,United States of America,0.00,1995.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45374,0.0,30840,en,"Yet another version of the classic epic, with ...",5.683753,Westdeutscher Rundfunk (WDR) Working Title Fil...,1991-05-13,0.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Robin Hood,5.7,NaN,NaN,35.0,Comedy,"Canada, Germany, United Kingdom, United States...",0.00,1991.0
45375,0.0,111109,tl,An artist struggles to finish his work while a...,0.178241,Sine Olivia,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,9.0,NaN,NaN,10402.0,Music,Philippines,0.00,2011.0
45376,0.0,67758,en,"When one of her hits goes wrong, a professiona...",0.903007,American World Pictures,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,3.8,NaN,NaN,35.0,Comedy,United States of America,0.00,2003.0
45377,0.0,227506,en,"In a small town live two brothers, one a minis...",0.003503,Yermoliev,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,0.0,NaN,NaN,18.0,Drama,Russia,0.00,1917.0
45378,0.0,461257,en,50 years after decriminalisation of homosexual...,0.163015,,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,0.0,NaN,NaN,10749.0,Romance,United Kingdom,0.00,2017.0

In [90]:
# Funcion de consulta del numero de peliculas por productora, ganancias totales y numero de peliculas
def productoras_exitosas(productora):

    lista_pelis_productoras = df[(df['production_companies'] == productora)].drop_duplicates(subset='id')

    cantidad_pelis_prod = (lista_pelis_productoras).shape[0]
    revenue_prod = lista_pelis_productoras['revenue'].sum()


    return {'productora':productora, 'ganancia_total':revenue_prod, 'cantidad':cantidad_pelis_prod}

In [91]:
# control sobre la funcion
productoras_exitosas('Pixar Animation Studios')

{'productora': 'Pixar Animation Studios',
 'ganancia_total': 2546355520.0,
 'cantidad': 28}

In [92]:
df.to_csv('API_movies_dataset.csv', index=False)